export const courses = [
  "Introduction to Computer Science",
  "Introduction to Programming",
  "Object Oriented Programming",
  "Data Structures and Algorithms",
  "Discrete Mathematics",
  "Computer Organization and Architecture",
  "Operating Systems",
  "Database Systems",
  "Computer Networks",
  "Systems Analysis and Design",
  "Software Engineering",
  "Web Programming",
  "Advanced Web Development",
  "Mobile Application Development",
  "Artificial Intelligence",
  "Machine Learning",
  "Human Computer Interaction",
  "Computer Security",
  "Distributed Systems",
  "Compiler Design",
  "Numerical Methods",
  "Algorithm Analysis and Design",
  "Data Mining",
  "Cloud Computing",
  "Research Methods",
  "Final Year Project",
  "Ethics in Computing",
];
export default courses;
